server.port=8080
spring.application.name=sysml-parser
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

app.baseFilePath=C:/Users/Pichau/git/sysml/src/main/java/sysml
app.systemLibPath=C:/Users/Pichau/Desktop/sysmlv2/SySML-v2-Pilot-Implementation/sysml.library

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true